
# origin 
# https://subicura.com/2017/02/10/docker-guide-for-beginners-create-image-and-deploy.html

# 1. ubuntu 설치 (패키지 업데이트 + 만든사람 표시)
FROM       ubuntu:16.04
MAINTAINER test@email.com
RUN        apt-get -y update

EXPOSE 4567
CMD    ls -all